# Generated by Django 3.1.5 on 2021-01-30 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_auto_20210125_0000'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='body',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='featured_section_1',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='featured_section_1_title',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='featured_section_2',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='featured_section_2_title',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='featured_section_3',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='featured_section_3_title',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='hero_cta',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='hero_cta_link',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='hero_text',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='image',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='promo_image',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='promo_text',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='promo_title',
        ),
    ]
